# Generated by Django 5.2.4 on 2025-07-12 23:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NutritionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('meal_type', models.CharField(choices=[('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner'), ('Snack', 'Snack'), ('Drink', 'Drink')], max_length=10)),
                ('notes', models.TextField(blank=True, null=True)),
                ('meal_photo', models.ImageField(blank=True, null=True, upload_to='meal_photos/')),
                ('calories', models.FloatField(blank=True, null=True)),
                ('protein', models.FloatField(blank=True, help_text='in grams', null=True)),
                ('carbohydrates', models.FloatField(blank=True, help_text='in grams', null=True)),
                ('fat', models.FloatField(blank=True, help_text='in grams', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
