# Generated by Django 5.2.4 on 2025-07-13 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutritionlog', '0003_nutritionlog_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutritionlog',
            name='data_source',
            field=models.CharField(choices=[('USER_INPUT', 'User Input'), ('PHOTO_ANALYSIS', 'Photo Analysis'), ('TYPICAL_DATA', 'Typical Data')], default='USER_INPUT', max_length=20),
        ),
    ]
