# Generated by Django 5.2.4 on 2025-07-13 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutritionlog', '0005_alter_nutritionlog_data_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutritionlog',
            name='ingredients',
            field=models.TextField(blank=True, help_text='Describe the ingredients for a more accurate nutrition analysis.', null=True),
        ),
    ]
