# Generated by Django 5.2.4 on 2025-07-13 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutritionlog', '0006_nutritionlog_ingredients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nutritionlog',
            name='data_source',
            field=models.CharField(choices=[('USER_INPUT', 'User Input'), ('PHOTO_ANALYSIS', 'Photo Analysis'), ('TYPICAL_DATA', 'Typical Data'), ('NOTES_ANALYSIS', 'Notes Analysis'), ('INGREDIENTS_ANALYSIS', 'Ingredients Analysis')], default='USER_INPUT', max_length=20),
        ),
    ]
