# Generated by Django 5.2.4 on 2025-07-13 22:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutritionlog', '0007_alter_nutritionlog_data_source'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g., 'Chicken Salad', 'Apple'", max_length=100)),
                ('calories', models.FloatField(blank=True, null=True)),
                ('protein', models.FloatField(blank=True, help_text='in grams', null=True)),
                ('carbohydrates', models.FloatField(blank=True, help_text='in grams', null=True)),
                ('fat', models.FloatField(blank=True, help_text='in grams', null=True)),
                ('saturated_fat', models.FloatField(blank=True, help_text='in grams', null=True)),
                ('cholesterol', models.FloatField(blank=True, help_text='in milligrams', null=True)),
                ('sodium', models.FloatField(blank=True, help_text='in milligrams', null=True)),
                ('potassium', models.FloatField(blank=True, help_text='in milligrams', null=True)),
                ('fiber', models.FloatField(blank=True, help_text='in grams', null=True)),
                ('sugars', models.FloatField(blank=True, help_text='in grams', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
