# Generated by Django 5.2.4 on 2025-07-14 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutritionlog', '0008_food'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='vitamin_c',
            field=models.FloatField(blank=True, help_text='in milligrams', null=True),
        ),
        migrations.AddField(
            model_name='nutritionlog',
            name='vitamin_c',
            field=models.FloatField(blank=True, help_text='in milligrams', null=True),
        ),
    ]
