# Generated by Django 5.2.4 on 2025-07-14 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutritionlog', '0009_food_vitamin_c_nutritionlog_vitamin_c'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='omega3_epa_dha',
            field=models.FloatField(blank=True, help_text='in grams', null=True, verbose_name='Omega-3 (EPA/DHA)'),
        ),
        migrations.AddField(
            model_name='nutritionlog',
            name='omega3_epa_dha',
            field=models.FloatField(blank=True, help_text='in grams', null=True, verbose_name='Omega-3 (EPA/DHA)'),
        ),
    ]
