# Generated by Django 5.2.4 on 2025-07-14 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutritionlog', '0010_food_omega3_epa_dha_nutritionlog_omega3_epa_dha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='omega3_epa_dha',
            field=models.FloatField(blank=True, help_text='in milligrams', null=True, verbose_name='Omega-3 (EPA/DHA)'),
        ),
        migrations.AlterField(
            model_name='nutritionlog',
            name='omega3_epa_dha',
            field=models.FloatField(blank=True, help_text='in milligrams', null=True, verbose_name='Omega-3 (EPA/DHA)'),
        ),
    ]
