# Generated by Django 5.2.4 on 2025-07-06 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0004_symptomlog_medication_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthrecordcomment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='medication',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='symptomlog',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
